[green_agent]
agentbeats_id = "019c17a2-82ec-7272-93cd-54082c74bfcd"
env = {}

[[participants]]
agentbeats_id = ""   # TODO: paste your purple agent AgentBeats ID here (Copy agent ID from Edit Agent page)
name = "purple_agent"
env = { ANTHROPIC_API_KEY = "${ANTHROPIC_API_KEY}" }

[config]
task_type = "issue_resolving"
output_dir = "/home/agent/results"
